name: Build CentOS 7 Buildbox Assets Images
run-name: Build CentOS 7 Buildbox Assets Images
on:
  # Only allow manual triggers
  workflow_dispatch:
  pull_request:

env:
  REGISTRY: ghcr.io
  BUILDBOX_BASE_NAME: ghcr.io/gravitational/teleport-buildbox

jobs:
  buildbox-centos7-assets:
    name: Build CentOS 7 Asset Buildbox
    strategy:
      matrix:
        # Build assets on x86 and ARM64.
        runner: ['self-hosted', 'linux', 'arm64']
    # Use bigger worker. Clang takes a while to build.
    runs-on: ${{ matrix.runner }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: ls ~
